apiVersion: v1
kind: Pod
metadata:
  labels:
    app: matrix-spring-boot-bot-examples
  name: matrix-spring-boot-bot-examples
spec:
  volumes:
    - name: matrix-spring-boot-bot-examples-synapse-volume
      hostPath:
        path: ./synapse
        type: DirectoryOrCreate
    - name: matrix-spring-boot-bot-examples-neo4j-volume
      hostPath:
        path: ./neo4j
        type: DirectoryOrCreate
  containers:
    - name: matrix-spring-boot-bot-examples-synapse
      env:
        - name: SYNAPSE_REPORT_STATS
          value: false
        - name: UID
          value: 0
        - name: GID
          value: 0
      image: docker.io/matrixdotorg/synapse:latest
      ports:
        - containerPort: 8008
          hostPort: 8008
          protocol: TCP
      volumeMounts:
        - name: matrix-spring-boot-bot-examples-synapse-volume
          mountPath: /data
      workingDir: /
    - name: matrix-spring-boot-bot-examples-neo4j
      env:
        - name: NEO4J_AUTH
          value: neo4j/secret
      image: neo4j:latest
      ports:
        - containerPort: 7474
          hostPort: 7474
          protocol: TCP
        - containerPort: 7687
          hostPort: 7687
          protocol: TCP
      volumeMounts:
        - name: matrix-spring-boot-bot-examples-neo4j-volume
          mountPath: /data
      workingDir: /