apiVersion: v1
kind: Pod
metadata:
  labels:
    app: matrix-spring-boot-bot-examples
  name: matrix-spring-boot-bot-examples
spec:
  volumes:
    - name: matrix-spring-boot-bot-examples-synapse-volume
      hostPath:
        path: ./synapse
        type: DirectoryOrCreate
  containers:
    - name: matrix-spring-boot-bot-examples-synapse
      env:
        - name: SYNAPSE_REPORT_STATS
          value: false
        - name: UID
          value: 0
        - name: GID
          value: 0
      image: docker.io/matrixdotorg/synapse:latest
      ports:
        - containerPort: 8008
          hostPort: 8008
          protocol: TCP
      volumeMounts:
        - name: matrix-spring-boot-bot-examples-synapse-volume
          mountPath: /data
      workingDir: /
